name: CI/CD Pipeline with Github Actions

on:
  push:
    branches:
      - sathsara

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 libapache2-mod-php composer
          composer install

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

      - name: Grant Permission
        run: chmod +x vendor/bin/phpunit

      - name: Run tests
        run: vendor/bin/phpunit tests/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup SSH connection to jump server 1
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Forward SSH port to EC2 instance 1
        run: |
          ssh-keyscan 43.205.199.65 >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -f -N -L 2222:172.20.3.120:22 ubuntu@43.205.199.65

      - name: Deploy code to EC2 instance 1
        run: |
          ssh-keyscan 43.205.199.65 >> ~/.ssh/known_hosts
          rsync -avz --delete --no-perms --exclude-from='.rsyncignore' -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222' ./ ubuntu@localhost:/var/www/html/app

      - name: Setup SSH connection to jump server 2
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Forward SSH port to EC2 instance 2
        run: |
          ssh-keyscan 13.234.67.142 >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -f -N -L 2223:172.20.4.162:22 ubuntu@13.234.67.142

      - name: Deploy code to EC2 instance 2
        run: |
          ssh-keyscan 13.234.67.142 >> ~/.ssh/known_hosts
          rsync -avz --delete --no-perms --exclude-from='.rsyncignore' -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2223' ./ ubuntu@localhost:/var/www/html/app